.MODEL SMALL

.DATA

MATRIX DB 5H,4H,3H,2H
       DB 6H,8H,4H,1H
       DB 7H,10H,3H,2H
       
TRANSPOSE DB 00H,00H,00H
          DB 00H,00H,00H
          DB 00H,00H,00H
          DB 00H,00H,00H         

.CODE

MOV BX,@DATA
MOV DS,BX
MOV CH,3H ;USING THIS AS A COUNTER FOR ALL MATRIX


JUMP2:
MOV BH,4H ;USING THIS AS COUNTER FOR ELEMENTS
JUMP1:

MOV AL,MATRIX[SI] 

MOV TRANSPOSE[DI],AL

INC SI    ;INCREMENTING BY 1 TO GO TO THE NEXT ELEMENT
ADD DI,3H ;INCREMENT DI TO BY 4 TO GO TO THE ELEMEMET BELOW PREVIOUS ELEMENT

DEC BH    ;AFTER MOVING EVERY ELEMENT BH WILL BE DECREMENT BY 1 EACH TIME 

JNZ JUMP1

SUB DI,0CH ;AFTER CONVERTING FIRST ROW INTO COLUMN
INC DI     ;DI WILL GO THE NEXT ELEMENT

DEC CH     ;AFTER FIRST CONVERSION CH(TOTAL MATRIX COUNTER WILL BE DECREMENT)

JNZ JUMP2

HLT        ;AFTER COMPLETING THE REQUIRED TASK THE PROGRAM WILL BE HLT

.EXIT